feat: add loongarch64 support
Signed-off-by: 吴小白 <296015668@qq.com>

diff --git a/.github/workflows/build-server-base.yml b/.github/workflows/build-server-base.yml
--- a/.github/workflows/build-server-base.yml
+++ b/.github/workflows/build-server-base.yml
@@ -1,9 +1,8 @@
 name: Build and Push Server Base Images
 
 on:
+  workflow_dispatch:
   push:
-    tags:
-      - "*"
     branches: [main]
   pull_request:
 
@@ -31,34 +30,110 @@ jobs:
             server:
               - 'server/**'
           force-filters: |
-            - '.github/workflows/build-server-base.yml'
-          force: ${{ startsWith(github.ref, 'refs/tags') || github.ref_name == 'main' }}
+            - '.github/workflows/build-server.yml'
+
+  matrix:
+    runs-on: ubuntu-latest
+    needs: pre-job
+    if: ${{ fromJSON(needs.pre-job.outputs.should_run).server == true }}
+    permissions:
+        contents: read
+    outputs:
+        matrix: ${{ steps.get-versions.outputs.result }}
+    steps:
+        - name: Checkout to repository
+          uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
+
+        - id: get-versions
+          name: Get dependency versions
+          uses: mikefarah/yq@1b9b4ac5187171d2e5e3129be0cfa827c7f9d53d # v4.53.3
+          with:
+            cmd: yq -n -o=json -I=0 '.target = ["dev", "prod"]'
 
   build_and_push:
-    needs: pre-job
-    uses: immich-app/devtools/.github/workflows/multi-runner-build.yml@50dc3a14f0606ecd8fc28d78d3a3c655115ab695 # multi-runner-build-workflow-v3.1.0
+    runs-on: ubuntu-latest
+    needs: [pre-job, matrix]
     if: ${{ fromJSON(needs.pre-job.outputs.should_run).server == true }}
     strategy:
-      fail-fast: true
-      matrix:
-        target: ["dev", "prod"]
-    permissions:
-      contents: read
-      actions: read
-      packages: write
-    with:
-      image: base-server-${{ matrix.target }}
-      context: server
-      dockerfile: server/Dockerfile
-      target: ${{ matrix.target }}
-      release-tag-type: git-tag
+      # Prevent a failure in one image from stopping the other builds
+      fail-fast: false
+      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
 
-  success-check:
-    needs: build_and_push
-    permissions: {}
-    runs-on: ubuntu-latest
-    if: always()
     steps:
-      - uses: immich-app/devtools/actions/success-check@81113db03f6d743efee81e0058c0b43f6cd6f36d # success-check-action-v0.0.6
+      - name: Checkout
+        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
         with:
-          needs: ${{ toJSON(needs) }}
+          fetch-depth: 0
+
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
+
+      - name: Login to GitHub Container Registry
+        uses: docker/login-action@c99871dec2022cc055c062a10cc1a1310835ceb4 # v4.3.0
+        with:
+          registry: ghcr.io
+          username: ${{ github.repository_owner }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Determine version change
+        id: changed-version
+        env:
+          BASE: ${{ github.event_name == 'pull_request' && format('origin/{0}', github.base_ref) || 'HEAD~1' }}
+        run: |
+          CHANGED_FILES=$(git diff --name-only $BASE...HEAD)
+          echo $CHANGED_FILES
+          if echo "$CHANGED_FILES" | grep -q -e "^server/" -e "^.github/workflows/build-server-base.yml$"; then
+            echo "any_changed=true" >> $GITHUB_OUTPUT
+          else
+            echo "any_changed=false" >> $GITHUB_OUTPUT
+          fi
+
+      - name: Determine image push
+        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
+        id: should-release
+        with:
+          script: |
+            if (context.eventName == "pull_request") return false;
+            if (context.eventName == "workflow_dispatch") return true;
+            return "${{ steps.changed-version.outputs.any_changed }}" == "true";
+
+      - name: Generate docker image tags
+        id: metadata
+        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
+        with:
+          flavor: |
+            # Disable latest tag
+            latest=false
+          images: |
+            name=ghcr.io/${{ github.repository_owner }}/immich-app/base-server-${{ matrix.target }}
+          tags: |
+            type=raw,value=202607211135
+
+      - name: Build and push image
+        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
+        with:
+          context: server/
+          platforms: linux/loong64
+          push: ${{ steps.should-release.outputs.result }}
+          cache-from: type=gha
+          cache-to: type=gha,mode=max
+          tags: ${{ steps.metadata.outputs.tags }}
+          target: ${{ matrix.target }}
+          labels: ${{ steps.metadata.outputs.labels }}
+
+  results:
+      if: ${{ always() }}
+      runs-on: ubuntu-latest
+      name: Image build success
+      needs: [build_and_push]
+      steps:
+        - run: |
+            result="${{ needs.build_and_push.result }}"
+            if [[ $result == "success" || $result == "skipped" ]]; then
+              exit 0
+            else
+              exit 1
+            fi
